language: python

matrix:
  include:
    - name: "Python 3.7 on Xenial Linux"
      python: 3.7
      node: node
    # It turns out that don't support python on macOS yet...... a pity
    # - name: "Python 3.7 on macOS"
    #  os: osx
    #  osx_image: xcode11
    #  language: shell
    #  env: PYTHON=37
    - name: "Python 3.7 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python nodejs.install
        - npm i -g npm
        - python -m pip install --upgrade pip
      env: PATH="/c/Python37:/c/Python37/Scripts:/c/Program Files/nodejs:$PATH"

cache:
  - npm
  - pip

before_install:
  - nvm install 10
  - npm i -g npm
  - pip3 install --upgrade pip

install:
  - npm ci
  - npm run dev
  - python setup.py install

script:
  - python setup.py sdist bdist_wheel
  - npm run build
  - sphinx-build -b html ./docs/ ./docs/_build/html

notifications:
    email: false

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $github_token
    local_dir: docs/_build/html
    on:
      branch: develop
      repo: TagnumElite/niftools_sphinx_theme
      python: 3.7
